<a href="https://colab.research.google.com/github/Nikithakadaparthi/Neural-network/blob/main/ICP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# QUE 1

class Employee:
    # DATA MEMBER TO COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("==========")

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("==========")


# INSTANCES FOR EMPLOYEE CLASS
emp1 = Employee('Akhila', '4', '1800000', 'Automation Tester')
# INSTANCE FOR FULL TIME EMPLOYEE
emp2 = Fulltime_Employee('Uday Kumar', '4', '1900000', 'Business Analyst', 'Fulltime')
emp3 = Fulltime_Employee('Nithya Reddy', '3', '2900000', 'Power BI Developer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()

Count of the Employees : 3
Average salary of the Employee: 600000.0
Employee Name: Akhila
Family Members: 4
Employee Annual Salary: 1800000
Department: Automation Tester
Employee Name : Uday Kumar
Family Members: 4
Employee Annual Salary: 1900000
Department: Business Analyst
Type of Employment : Fulltime
Employee Name : Nithya Reddy
Family Members: 3
Employee Annual Salary: 2900000
Department: Power BI Developer
Type of Employment : Fulltime


In [ ]:
# QUE 2

import numpy as np

# creating array of size as 20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 cross 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the maximum in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the maximum in each row : \n", random_vector)

Random Vector : 
 [ 8.37786464  7.38753374  5.75924559  8.17057456 15.58180591 18.83504107
 19.98837123 11.79718365 16.7741499  16.80435349  2.86169706 17.08650967
  8.47578347 11.93110063 10.73893175 19.74079902 16.31842599 17.97240882
  6.25517314  1.62688415]
after reshaping (4 by 5): 
 [[ 8.37786464  7.38753374  5.75924559  8.17057456 15.58180591]
 [18.83504107 19.98837123 11.79718365 16.7741499  16.80435349]
 [ 2.86169706 17.08650967  8.47578347 11.93110063 10.73893175]
 [19.74079902 16.31842599 17.97240882  6.25517314  1.62688415]]
Replacing the maximum in each row : 
 [[ 8.37786464  7.38753374  5.75924559  8.17057456  0.        ]
 [18.83504107  0.         11.79718365 16.7741499  16.80435349]
 [ 2.86169706  0.          8.47578347 11.93110063 10.73893175]
 [ 0.         16.31842599 17.97240882  6.25517314  1.62688415]]
